name: Simple CI Workflow
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Hello GitHub Actions"
      - run: date
      - run: echo ${{ github.ref_name }}
      - name: Run unit tests
        run: pytest
      - name: Tests passed
        if: success()
        run: echo "All tests passed successfully!"
      - name: Tests failed
        if: failure()
        run: echo "Tests failed. Please check the logs."